// <auto-generated> 此文件由 ExcelTool 自动生成，请勿手动修改。

namespace Game.Config;

/// <summary>Hero 配置表数据行。</summary>
public sealed class HeroMeta
{
    /// <summary>
    /// ID - 唯一主键
    /// </summary>
    public uint Id;
    /// <summary>
    /// 名字 - 名字
    /// </summary>
    public string Name;
    /// <summary>
    /// 生命值
    /// </summary>
    public float Hp;
}
