using System.Text;
using ExcelTool.Models;

namespace ExcelTool.CodeGen;

/// <summary>
/// 根据 TableData 生成 {TableName}Meta.cs 文件。
/// </summary>
public static class MetaCodeGenerator
{
    public static void Generate(TableData table, string outputDir, string namespaceName)
    {
        var className = $"{table.Name}Meta";
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated> 此文件由 ExcelTool 自动生成，请勿手动修改。");
        sb.AppendLine();
        sb.AppendLine($"namespace {namespaceName};");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>{table.Name} 配置表数据行。</summary>");
        sb.AppendLine($"public sealed class {className}");
        sb.AppendLine("{");

        foreach (var column in table.Columns)
        {
            AppendFieldComment(sb, column);
            sb.AppendLine($"    public {ToCSharpType(column.Type)} {ToPascalCase(column.Name)};");
        }

        sb.AppendLine("}");

        Directory.CreateDirectory(outputDir);
        var outputPath = Path.Combine(outputDir, $"{className}.cs");
        File.WriteAllText(outputPath, sb.ToString(), Encoding.UTF8);
    }

    private static void AppendFieldComment(StringBuilder sb, ColumnDef column)
    {
        var summary = column.Alias;
        if (!string.IsNullOrWhiteSpace(column.Desc))
            summary = string.IsNullOrWhiteSpace(summary)
                ? column.Desc
                : $"{summary} - {column.Desc}";

        if (string.IsNullOrWhiteSpace(summary))
            return;

        sb.AppendLine("    /// <summary>");
        sb.AppendLine($"    /// {summary}");
        sb.AppendLine("    /// </summary>");
    }

    private static string ToCSharpType(FieldType type) =>
        type switch
        {
            FieldType.UInt => "uint",
            FieldType.String => "string",
            FieldType.Float => "float",
            _ => "object",
        };

    /// <summary>字段名 id → Id，hp → Hp。</summary>
    private static string ToPascalCase(string name) =>
        string.IsNullOrEmpty(name) ? name : char.ToUpperInvariant(name[0]) + name[1..];
}
